[
    {
        "Username":"Jane",
        "Password":"Jane123"
    },
    {
        "Username":"John",
        "Password":"John123"
    },
    {
        "Username":"Peter",
        "Password":"Peter123"
    }
]